//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ces3
    {
        public string city_name { get; set; }
        public Nullable<int> city_id { get; set; }
        public string typename { get; set; }
        public long count { get; set; }
    }
}
